[phases.setup]
nixPkgs = ['nodejs_18', 'npm-9_x']

[phases.install]
cmd = 'npm ci'

[phases.build]
cmd = 'npx nx build @keystone/cms'

[phases.start]
cmd = 'cd apps/front-ends/cms && npx next start -p $PORT'
