import './global.css';
import { MainNavigation } from './components/navigation/MainNavigation/MainNavigation';

export const metadata = {
  title: 'Welcome to cms',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
