import { Injectable, Logger, HttpException, HttpStatus } from "@nestjs/common";
import { FirebaseServerClient } from "@keystone/auth";
import { Tenant, Corporation, TenantMembership } from "@keystone/database";
import mongoose from "mongoose";

export interface CreateTenantRequest {
  name: string;
  userId: string; // Firebase UID of the user creating the tenant
  userEmail: string;
}

export interface CreateTenantResponse {
  success: boolean;
  tenantId: string;
  corporationId: string;
  message: string;
}

@Injectable()
export class TenantService {
  private readonly logger = new Logger(TenantService.name);
  private readonly firebaseClient: FirebaseServerClient;

  constructor() {
    this.firebaseClient = new FirebaseServerClient();
  }

  /**
   * Create a new tenant with corporation and set up user as owner
   * This method handles both Firebase GIP tenant creation and local database setup
   */
  async createTenant(request: CreateTenantRequest): Promise<CreateTenantResponse> {
    try {
      this.logger.log(`🔄 Starting tenant creation for user ${request.userId}`);

      // Validate tenant name (no special characters)
      if (!this.isValidTenantName(request.name)) {
        throw new HttpException(
          "Tenant name can only contain letters, numbers, and spaces",
          HttpStatus.BAD_REQUEST
        );
      }

      // Check if user already has a tenant
      const existingMembership = await TenantMembership.findOne({
        userId: request.userId,
        isActive: true
      });

      if (existingMembership) {
        throw new HttpException(
          "User already belongs to a tenant",
          HttpStatus.CONFLICT
        );
      }

      // Step 1: Create tenant in Google Identity Platform (Firebase)
      this.logger.log("🔄 Creating tenant in Google Identity Platform...");

      let gipTenantId: string;

      try {
        // Sanitize display name for Firebase (Firebase has stricter requirements)
        const firebaseDisplayName = this.sanitizeFirebaseDisplayName(request.name);
        this.logger.log(`📝 Original name: "${request.name}"`);
        this.logger.log(`📝 Sanitized Firebase display name: "${firebaseDisplayName}"`);
        this.logger.log(`📝 Display name length: ${firebaseDisplayName.length}`);

        const tenantConfig = {
          tenantId: "", // Will be generated by GIP
          displayName: firebaseDisplayName,
          allowPasswordSignup: true,
          enableEmailLinkSignin: true
        };

        this.logger.log(`📝 Full tenant config:`, JSON.stringify(tenantConfig, null, 2));

        this.logger.log(`🔍 Firebase client type: ${typeof this.firebaseClient}`);
        this.logger.log(`🔍 Firebase client methods: ${Object.getOwnPropertyNames(Object.getPrototypeOf(this.firebaseClient))}`);

        // Only pass displayName to Firebase (other options are not supported by Firebase Admin SDK)
        const gipTenant = await this.firebaseClient.createTenant({
          displayName: firebaseDisplayName
        });

        this.logger.log(`🔍 Firebase response type: ${typeof gipTenant}`);
        this.logger.log(`🔍 Firebase response:`, JSON.stringify(gipTenant, null, 2));

        if (!gipTenant || !(gipTenant as any).tenantId) {
          throw new Error("No tenantId returned from Firebase");
        }

        gipTenantId = (gipTenant as any).tenantId;
        this.logger.log(`✅ GIP tenant created with ID: ${gipTenantId}`);

      } catch (firebaseError) {
        this.logger.error(`❌ Firebase tenant creation failed:`, firebaseError);
        throw new HttpException(
          `Failed to create tenant in Google Identity Platform: ${firebaseError instanceof Error ? firebaseError.message : 'Unknown error'}`,
          HttpStatus.INTERNAL_SERVER_ERROR
        );
      }

      // Step 2: Create local tenant record in MongoDB
      this.logger.log("🔄 Creating local tenant record...");
      const tenant = new Tenant({
        name: request.name,
        gipTenantId: gipTenantId
      });

      await tenant.save();
      this.logger.log(`✅ Local tenant record created with ID: ${tenant._id}`);

      // Step 3: Create corporation in MongoDB
      this.logger.log("🔄 Creating corporation...");
      const corporation = new Corporation({
        name: request.name,
        tenantId: tenant._id.toString()
      });

      await corporation.save();
      this.logger.log(`✅ Corporation created with ID: ${corporation._id}`);

      // Step 4: Add user to the Firebase GIP tenant
      this.logger.log("🔄 Adding user to Firebase GIP tenant...");
      try {
        // First, get the user from Firebase (they should exist in the default tenant)
        const userRecord = await this.firebaseClient.getUserByUid(request.userId);
        if (!userRecord) {
          throw new Error("User not found in Firebase");
        }

        // Add user to the new GIP tenant
        await this.firebaseClient.addUserToTenant(request.userId, gipTenantId);
        this.logger.log(`✅ User added to Firebase GIP tenant`);
      } catch (firebaseError) {
        this.logger.error(`❌ Failed to add user to Firebase GIP tenant:`, firebaseError);
        // Don't fail the entire operation, but log the error
      }

      // Step 5: Create tenant membership for user (as owner)
      this.logger.log("🔄 Creating tenant membership for user...");
      const membership = new TenantMembership({
        userId: request.userId,
        tenantId: tenant._id.toString(),
        roles: ["owner"],
        isActive: true
      });

      await membership.save();
      this.logger.log(`✅ Tenant membership created for user`);

      this.logger.log(`✅ Tenant creation completed successfully`);

      return {
        success: true,
        tenantId: tenant._id.toString(),
        corporationId: corporation._id.toString(),
        message: `Tenant "${request.name}" created successfully`
      };

    } catch (error) {
      this.logger.error(`❌ Tenant creation failed:`, error);

      if (error instanceof HttpException) {
        throw error;
      }

      throw new HttpException(
        `Failed to create tenant: ${error instanceof Error ? error.message : "Unknown error"}`,
        HttpStatus.INTERNAL_SERVER_ERROR
      );
    }
  }

  /**
   * Check if user needs to create a tenant
   */
  async checkTenantRequirement(userId: string): Promise<{ needsTenant: boolean; existingTenantId?: string }> {
    try {
      const membership = await TenantMembership.findOne({
        userId: userId,
        isActive: true
      });

      if (membership) {
        return {
          needsTenant: false,
          existingTenantId: membership.tenantId
        };
      }

      return { needsTenant: true };
    } catch (error) {
      this.logger.error(`❌ Failed to check tenant requirement:`, error);
      // Default to requiring tenant creation if check fails
      return { needsTenant: true };
    }
  }

  /**
   * Get user's active tenant and corporation
   */
  async getUserActiveTenant(userId: string): Promise<{
    tenantId: string;
    corporationId: string;
    roles: string[];
  } | null> {
    try {
      const membership = await TenantMembership.findOne({
        userId: userId,
        isActive: true
      }).populate("tenantId corporationId");

      if (!membership) {
        return null;
      }

      return {
        tenantId: membership.tenantId,
        corporationId: membership.corporationId || "",
        roles: membership.roles
      };
    } catch (error) {
      this.logger.error(`❌ Failed to get user active tenant:`, error);
      return null;
    }
  }

  /**
   * Validate tenant name (no special characters)
   */
  private isValidTenantName(name: string): boolean {
    // Allow letters, numbers, spaces, and common punctuation
    const validNameRegex = /^[a-zA-Z0-9\s\-_&.()]+$/;
    return validNameRegex.test(name) && name.trim().length >= 2 && name.trim().length <= 100;
  }

  /**
   * Sanitize display name for Firebase tenant creation
   * Firebase has very strict requirements for tenant display names:
   * - 1-63 characters
   * - Only alphanumeric, hyphens, and underscores (NO SPACES)
   * - Must start with a letter or number
   * - Cannot end with a hyphen
   */
  private sanitizeFirebaseDisplayName(name: string): string {
    // For debugging, let's try the most basic approach first
    // Convert to lowercase alphanumeric only
    let sanitized = name.toLowerCase().replace(/[^a-z0-9]/g, '');

    // If too short, add prefix
    if (sanitized.length < 3) {
      sanitized = 'org' + sanitized;
    }

    // Limit to reasonable length
    sanitized = sanitized.substring(0, 20);

    // If empty after sanitization, use a default
    if (!sanitized || sanitized.length === 0) {
      sanitized = 'organization';
    }

    return sanitized;
  }

  /**
   * Delete a tenant from both GIP and local database
   * This method handles both Firebase GIP tenant deletion and local database cleanup
   */
  async deleteTenant(tenantId: string, gipTenantId: string): Promise<{ success: boolean; message: string }> {
    try {
      this.logger.log(`🔄 Starting tenant deletion for tenant ${tenantId} (GIP: ${gipTenantId})`);

      // Step 1: Delete tenant from Google Identity Platform (Firebase)
      if (gipTenantId) {
        this.logger.log("🔄 Deleting tenant from Google Identity Platform...");

        try {
          await this.firebaseClient.deleteTenant(gipTenantId);
          this.logger.log(`✅ GIP tenant deleted successfully: ${gipTenantId}`);
        } catch (firebaseError) {
          this.logger.error(`❌ Firebase tenant deletion failed:`, firebaseError);
          // Continue with local deletion even if GIP deletion fails
          this.logger.warn(`⚠️ Proceeding with local deletion despite GIP failure`);
        }
      }

      // Step 2: Delete local tenant record and related data
      this.logger.log("🔄 Deleting local tenant data...");

      // Delete tenant memberships first (foreign key constraint)
      const deletedMemberships = await TenantMembership.deleteMany({ tenantId: new mongoose.Types.ObjectId(tenantId) });
      this.logger.log(`✅ Deleted ${deletedMemberships.deletedCount} tenant memberships`);

      // Delete corporations associated with this tenant
      const deletedCorporations = await Corporation.deleteMany({ tenantId: new mongoose.Types.ObjectId(tenantId) });
      this.logger.log(`✅ Deleted ${deletedCorporations.deletedCount} corporations`);

      // Delete the tenant itself
      const deletedTenant = await Tenant.findByIdAndDelete(tenantId);
      if (!deletedTenant) {
        throw new HttpException(
          `Tenant with ID "${tenantId}" not found`,
          HttpStatus.NOT_FOUND
        );
      }

      this.logger.log(`✅ Local tenant deleted successfully: ${tenantId}`);

      return {
        success: true,
        message: `Tenant "${deletedTenant.name}" deleted successfully from both GIP and local database`
      };
    } catch (error) {
      this.logger.error(`❌ Tenant deletion failed:`, error);
      throw error;
    }
  }
}
